services:
  backend:
    build: ./backend
    container_name: pdxmas-backend
    ports:
      - "3001:3001"
    volumes:
      - ./data:/app/data
      - ./uploads:/app/uploads
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DATABASE_PATH=/app/data/contest.db
    restart: unless-stopped
    networks:
      - pdxmas-network

  frontend:
    build: ./frontend
    container_name: pdxmas-frontend
    ports:
      - "3099:80"
#    depends_on:
#      backend:
#        condition: service_healthy
    restart: unless-stopped
    networks:
      - pdxmas-network

networks:
  pdxmas-network:
    driver: bridge
